GET  http://127.0.0.1:3000/users/me HTTP/2.0
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTljN2ZlMTBiZDUyMjY1MWYzZDgyZTMiLCJpYXQiOjE1ODczMTQ2NTd9.ywcrY0dsfm_es-Qm4AKbqAt4ojfdvkb1-z0RZPsItag